recipe: default.v1
language: en

pipeline:
  - name: "WhitespaceTokenizer"
  - name: "RegexFeaturizer"
    #  - name: "spellchecking.CorrectSpelling"
    case_sensitive: False
    use_lookup_tables: True
    use_regexes: True
    "use_word_boundaries": True
  - name: "LexicalSyntacticFeaturizer"
  - name: "CountVectorsFeaturizer"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  # - name: "CRFEntityExtractor"
  - name: "RegexEntityExtractor"
  - name: "DIETClassifier"
    batch_strategy: sequence
    epochs: 20
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 20
    retrieval_intent: chitchat
  - name: ResponseSelector
    epochs: 20
    retrieval_intent: evis
  # - name: FallbackClassifier
  #   threshold: 0.3
  #   ambiguity_threshold: 0.1

policies:
  - name: TEDPolicy
    max_history: 5
    epochs: 20
    batch_size: 50
    max_training_samples: 300
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
